pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hld'
            }
        }
        stage('Hi') {
            steps {
                echo 'Hello'
            }
        }
    }
}
