pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World'
            }
        }
    }
      stages {
        stage('Hi') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
